context("Make sure plots are properly generated by sourceryReport")
library(SeuratSourcery)

test_that("getSourceryReport produces valid tables and plots", {
  runes <- list(A = demo_small(), B = demo_small())
  rep <- runeInspection(runes)

  out <- getSourceryReport(rep, show_plots = FALSE)

  expect_true("summary" %in% names(out))
  expect_true("qc" %in% names(out))
  expect_true("overlap" %in% names(out))
  expect_true("conserved" %in% names(out))
  expect_true("plots" %in% names(out))

  # check plots are ggplot objects
  expect_true(all(vapply(out$plots, inherits, logical(1), what = "gg")))
})

# [END]
